// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNkqr29LU8KN9pOajHuuqmoNFFYEBV2xk',
    appId: '1:214010796188:web:03f6be3918164f3f443559',
    messagingSenderId: '214010796188',
    projectId: 'pornosocial-c003d',
    authDomain: 'pornosocial-c003d.firebaseapp.com',
    databaseURL:
        'https://pornosocial-c003d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pornosocial-c003d.firebasestorage.app',
    measurementId: 'G-3H4VNS4NTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC97oxJT-ZSqEtWco9dtUxQlUVtW_OofI0',
    appId: '1:214010796188:android:695d4449b6a9a129443559',
    messagingSenderId: '214010796188',
    projectId: 'pornosocial-c003d',
    storageBucket: 'pornosocial-c003d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3uLAT_ksEnih3S9d8uQKyXv071vShqW4',
    appId: '1:214010796188:ios:0f227da4e5dff8a2443559',
    messagingSenderId: '214010796188',
    projectId: 'pornosocial-c003d',
    storageBucket: 'pornosocial-c003d.firebasestorage.app',
    iosBundleId: 'com.pornosocial.pornoSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3uLAT_ksEnih3S9d8uQKyXv071vShqW4',
    appId: '1:214010796188:ios:0f227da4e5dff8a2443559',
    messagingSenderId: '214010796188',
    projectId: 'pornosocial-c003d',
    storageBucket: 'pornosocial-c003d.firebasestorage.app',
    iosBundleId: 'com.pornosocial.pornoSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNkqr29LU8KN9pOajHuuqmoNFFYEBV2xk',
    appId: '1:214010796188:web:d94d8eb65825c1ba443559',
    messagingSenderId: '214010796188',
    projectId: 'pornosocial-c003d',
    authDomain: 'pornosocial-c003d.firebaseapp.com',
    databaseURL:
        'https://pornosocial-c003d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pornosocial-c003d.firebasestorage.app',
    measurementId: 'G-EP3JWJ55HR',
  );
}
